# Generated by Django 5.2.7 on 2025-10-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="news",
            name="title",
            field=models.TextField(blank=True),
        ),
    ]
